### ISSUE TITLE
! placeholder no longer accepted in drupal 8

### ISSUE THREAD

**Issue by HellooooNewman** [alexfinnarn/drupal-twitter-feed#2]
https://www.drupal.org/node/2575819

You have to use `@` when passing placeholders now. You also can't pass html in the variable, you'll need to move some stuff from the block build function to the template.

**Comment by alexfinnarn** [comment]
Thanks @HellooooNewman! I'm surprised anyone is looking at this module, actually. I would think there are way better Twitter block solutions out there for D8, but I'm glad this code helped you out in some way :)
